package com.zeafen.petwalker.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF516527)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD3EC9E)
val onPrimaryContainerLight = Color(0xFF3A4D10)
val secondaryLight = Color(0xFF5A6148)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDEE6C5)
val onSecondaryContainerLight = Color(0xFF424A31)
val tertiaryLight = Color(0xFF396660)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBCECE4)
val onTertiaryContainerLight = Color(0xFF204E48)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFAFAEE)
val onBackgroundLight = Color(0xFF1A1C15)
val surfaceLight = Color(0xFFFAFAEE)
val onSurfaceLight = Color(0xFF1A1C15)
val surfaceVariantLight = Color(0xFFE2E4D4)
val onSurfaceVariantLight = Color(0xFF45483C)


val primaryDark = Color(0xFFB7D084)
val onPrimaryDark = Color(0xFF253600)
val primaryContainerDark = Color(0xFF3A4D10)
val onPrimaryContainerDark = Color(0xFFD3EC9E)
val secondaryDark = Color(0xFFC2CAAA)
val onSecondaryDark = Color(0xFF2C331D)
val secondaryContainerDark = Color(0xFF424A31)
val onSecondaryContainerDark = Color(0xFFDEE6C5)
val tertiaryDark = Color(0xFFA0D0C8)
val onTertiaryDark = Color(0xFF013732)
val tertiaryContainerDark = Color(0xFF204E48)
val onTertiaryContainerDark = Color(0xFFBCECE4)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF12140D)
val onBackgroundDark = Color(0xFFE3E3D7)
val surfaceDark = Color(0xFF12140D)
val onSurfaceDark = Color(0xFFE3E3D7)
val surfaceVariantDark = Color(0xFF45483C)
val onSurfaceVariantDark = Color(0xFFC6C8B9)